### ISSUE TITLE
[Feature] Save indicator

### ISSUE THREAD

**Issue by Infinitay** [Notespeon/casket-saver#4]
Would you consider adding some kind of indicator to the plugin to let the user know that they can't open a casket due to the plugin? Perhaps one of the following indications would suffice:

- As a chat message when the user tries to use the chest while the save feature is active
- Whenever a casket is added to your inventory
	- I'm not sure if withdrawing more than one at a time will cause the event to fire multiple times
- As a tooltip over the casket
- As an infobox

**Comment by TheLope** [comment]
```As a chat message when the user tries to use the chest while the save feature is active```
Added in #7
